services:
  rabbitmq:
    image: rabbitmq:3.11.26-management #buscar no docker hub a image 
    container_name: rabbitmq
    ports:
      - "5672:5672"       # RabbitMQ main port
      - "15672:15672"     # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin 